title:             Sanjay Seshan
email:            sanjay@seshan.org
description:      My work. My interests.
author:
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://blackrockdigital.github.io"

# Social Profiles
twitter_username:  SeshanBrothers
github_username:   SanjaySeshan
facebook_username: Sanjay.Seshan1

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
