title:            Sanjay Seshan
email:            sanjay@seshan.org
# description:      My work. My interests.
author:
baseurl:           ""
url:               "http://sanjay.seshan.org"

# Social Profiles
# twitter_username:  SeshanBrothers
github_username:   SanjaySeshan
facebook_username: Sanjay.Seshan1
linkedin_username: sanjayseshan

# Build settings
markdown:          kramdown
paginate:          20
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
